Ethan - Add effective capacity
ucsb-cs156-m23/proj-happycows-m23-10am-1 pull request #39
Opened 2023-08-24 19:51 UTC by EthanSun210

In this PR, I added effective capacity so that the cows' health is updated according to the effective capacity.

Closes: #4

2023-08-24 21:18 UTC, haostevewu approved these changes, later dismissed
LGTM

2023-08-24 21:32 UTC, GDW1 requested changes
Update the name to be more specific. I.E. Add to where

I let another PR with a bad name be merged but you should definitely be more specific

2023-08-25 01:57 UTC, ZixiaoJin commented
LGTM

2023-08-25 13:09 UTC, EthanSun210 commented
> 

I've modified the description of the PR.

2023-08-25 20:55 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
> +        joinedCommons.setNumUsers(joinedCommons.getNumUsers() + 1);
This approach is not acceptable.   It adds redundant state to the Commons, and violated database normalization principles.  There is already a method on the commonsRepository for getting the number of  users.  That is how this must be implemented.   Other teams were forced to change their code after implementing this approach.

2023-08-25 21:08 UTC, pconrad requested changes
This is not mergeable in its current form, because it uses an incorrect approach, one that sets a trap for future developers.

If you had submitted this earlier, we would have had time to discuss alternative approaches.  
There is very little time left, but if you want to try an alternative, here's an outline.  To be clear, you aren't required to do this, and I'm not really expecting you to, but if you wanted to try, this is how you could go about it.

(1) For the jobs, instead of adding effective capacity to the Commons entity, you can add a function that calculates it from two parameters: a Commons, and a CommonsRepository.  The CommonsRepository has this method to return the number of cows:

https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-1/blob/3bb2ffeafec58ee9029cefa5c604c5e0ce4ef974/src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonsRepository.java#L17C4-L18C51

So this: 
* `commons.getEffectiveCapacity()`
Would be replaced  by:
* `calculateEffectiveCapacity(commons, commonsRepository)`

You might also need to change the parameters that the health strategies take so that you can get that value into that object.

(2) This may or may not be necessary, but if you need the value to display in the frontend, you can add the effective capacity to the CommonsPlus object here: 

https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-1/blob/main/src/main/java/edu/ucsb/cs156/happiercows/entities/CommonsPlus.java

This object is initialized in this method of the Commons controller: 

https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-1/blob/3bb2ffeafec58ee9029cefa5c604c5e0ce4ef974/src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java#L264

2023-08-25 21:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
> +    private int numUsers;
This is not permitted.

2023-08-27 05:11 UTC, pconrad commented
It appears you won't be working on this, so closing it.

2023-08-27 05:11 UTC, closed without merging